version: "3.8"
name: "rails-coursework"
services:
  db:
    image: "postgres:16.2"
    container_name: "coursework-postgresql"
    ports:
      - "5400:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
  backend:
    build: "backend"
    working_dir: "/app"
    container_name: "coursework-rails"
    restart: always
    depends_on:
      - db
    ports:
      - "5401:5401"
    volumes:
      - "./backend:/app"
    stdin_open: true
    tty: true
  frontend:
    build: "./frontend"
    working_dir: "/app"
    container_name: "coursework-react"
    restart: always
    depends_on:
      - backend
    ports:
      - "5402:5402"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
  commitlinter:
    build:
      context: ./
      dockerfile: ./commitlinter/Dockerfile
    container_name: "coursework-commitlinter"
    restart: always
    volumes:
      - "./.git:/app/.git"
      - "./commitlint.config.js:/app/commitlint.config.js"
    stdin_open: true
    tty: true
