version: "3.8"
name: "rails-coursework"
services:
  db:
    image: "postgres:16.2"
    container_name: "coursework-postgresql"
    ports:
      - "5400:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
  redis:
    image: "redis:7.2.4-alpine"
    container_name: "coursework-redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/d–∞ta:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=root
  backend:
    build: "backend"
    working_dir: "/app"
    container_name: "coursework-rails"
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "5401:5401"
    volumes:
      - "./backend:/app"
    stdin_open: true
    tty: true
  frontend:
    build: "./frontend"
    working_dir: "/app"
    container_name: "coursework-react"
    restart: always
    depends_on:
      - backend
    ports:
      - "5402:5402"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
